services:
  tk-atlas:
    image: mongodb/mongodb-atlas-local:8
    container_name: tk-atlas
    hostname: "0fa6568f05e0"  # <- IL TRUCCO JEDI
    ports:
      - "27018:27017"
    volumes:
      - /Users/renzosala/Develop/personal/tokeniko/atlas/data:/data/db
      - /Users/renzosala/Develop/personal/tokeniko/atlas/config:/data/configdb
      - /Users/renzosala/Develop/personal/tokeniko/atlas/mongot:/data/mongot
    restart: unless-stopped